version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: nutri-info-mongo
    ports:
      - 27017:27017
    volumes:
      - nutri-info-data:/nutri-info-data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    
  mongo-express:
    image: mongo-express
    container_name: nutri-info-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - MONGO_HOST=nutri-info-mongo
      - MONGO_URI=mongodb://mongo:27017/nutri-info?useNewUrlParser=true&useUnifiedTopology=true


volumes:
  nutri-info-data: {}

networks:
  default:
    name: mongodb_network