= Nutrition Information Service

The Nutrition Information Service is a microservice that provides information about the nutritional value of the dishes.
Specifically, it provides the following information:
    - The list of ingredients of a dish.
    - The nutritional composition of an ingredient.
    - The nutritional composition of a dish is the sum of the nutritional composition of its ingredients.
    - Using The Plate Method provides information on whether the dish is nutritionally balanced.
    - If the dish is suitable for vegan people or not.
What's more, it allows the addition of new ingredients and dishes to the database.

This service is written in Reactive Java and uses the Spring WebFlux framework and MongoDB as a database.

== Instalation

To install this project, follow these steps:

1. Clone the repository from GitHub:
  https://github.com/analicia97/nutrition_info.git

2. Run de Docker Machine in your device.

3. Open the repository with your favourite IDE.

== Repository Structure

-  root -- project configuration files and docker-compose file
- `src/main/java` -- Java source code
- `src/main/resources` -- resources
- `src/test/java` -- test source code
- `src/test/resources` -- test resources

== Branches

- `main` -- code of the actual release
- `develop` -- development of the next release
- `feature/` -- feature development
- `bugfix/` -- bugfix development
- `hotfix/` -- hotfix development

